default: FALSE
MD003:
    style: atx
MD007:
    indent: 2
# Allow arbitrary line length
#
# Reason: We apply the one-sentence-per-line rule. A sentence may get longer than 80 characters, especially if links are contained.
#
# Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
MD013: false
MD033: true
no-inline-html:
    allowed_elements:
        - br
        - img
        - picture
        - video
        - small
        - strong
        - detials
        - summary
        - b
        - div
no-hard-tabs: false
whitespace: false
